### ISSUE TITLE
Renaming .../ace to something else

### ISSUE THREAD

**Issue by ghost** [rbxb/place#13]
Ok so I finally setup my place on the localhost and I saw that the url to the main page is localhost:8080/ace, so I don't like the ace at the end of the url, is it possible to rename it to something else? Thanks.

**Comment by rbxb** [comment]
Yes. In [web/root/_filters.txt](https://github.com/rbxb/place/blob/master/web/root/_filters.txt). Currently it says:
```
#serve ace desktop.html
```
So when someone goes to the path `ace` it will serve the file named `desktop.html`.
You can change `ace` to be whatever you want.

You should also change [web/_filters.txt](https://github.com/rbxb/place/blob/master/web/_filters.txt) so that entering no path redirects you to whatever you chose. Currently it says:
```
#redirect * ./ace
```
which redirects `localhost:8080` to `localhost:8080/ace`

**Comment by ghost** [comment]
> Yes. In [web/root/_filters.txt](https://github.com/rbxb/place/blob/master/web/root/_filters.txt). Currently it says:
> 
> ```
> #serve ace desktop.html
> ```
> 
> So when someone goes to the path `ace` it will serve the file named `desktop.html`. You can change `ace` to be whatever you want.
> 
> You should also change [web/_filters.txt](https://github.com/rbxb/place/blob/master/web/_filters.txt) so that entering no path redirects you to whatever you chose. Currently it says:
> 
> ```
> #redirect * ./ace
> ```
> 
> which redirects `localhost:8080` to `localhost:8080/ace`

Ok thanks
